const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const classes = () => ({ values: new Set(), toggle(key, active) { active ? this.values.add(key) : this.values.delete(key); } });
const badge = { classList: classes() }, activity = {}, freshness = {};
const board = { dataset: {}, classList: classes(), querySelector(s) { return s === '[data-board-status]' ? badge : activity; } };
const card = { classList: classes(), closest() { return board; }, querySelector() { return freshness; } };
const toggle = { checked: true };
const context = { document: { querySelectorAll() { return [card]; }, getElementById() { return toggle; } } };
vm.createContext(context);
vm.runInContext(fs.readFileSync(require('node:path').join(__dirname, '../public/assets/js/gauge-status.js'), 'utf8'), context);
const response = { values: [59, 0], current: false, boardOnline: true, boardLabel: 'Online', activityLabel: '8/14 aktuell', activityHint: 'summary', freshnessLabel: 'Veraltet', lastReceivedAt: '2026-09-01T12:00:00Z' };
context.updateGaugeStatus(59, response);
assert.equal(card.classList.values.has('disabled'), true);
assert.equal(activity.textContent, '8/14 aktuell');
assert.equal(board.classList.values.has('dashboard-board-hidden'), false);
context.updateGaugeStatus(59, {...response, current: true, freshnessLabel: 'Aktuell'});
assert.equal(card.classList.values.has('disabled'), false, 'Fresh receipt must re-enable a stale gauge without reloading.');
context.updateGaugeStatus(59, {...response, boardOnline: false});
assert.equal(board.classList.values.has('dashboard-board-hidden'), true);
assert.equal(badge.classList.values.has('bg-danger'), true);
toggle.checked = false;
context.updateGaugeStatus(59, {...response, boardOnline: false});
assert.equal(board.classList.values.has('dashboard-board-hidden'), false);
assert.ok(freshness.textContent.startsWith('Veraltet'));
console.log('Gauge status tests passed.');
